-- 베이스라인. Hibernate의 ddl-auto: update 가 만들어 놓은 최초 스키마를 그대로 옮긴 것.
--
-- 이미 테이블이 있는 기존 DB에서는 baseline-on-migrate 설정에 의해 이 파일이 실행되지 않고
-- "적용된 것으로" 기록만 된다. 빈 DB(새 PC, CI)에서는 실제로 실행된다.
-- 두 경로가 같은 결과에 도달해야 하므로 내용을 임의로 바꾸지 말 것.

CREATE TABLE schedule (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    start_at    TIMESTAMP(6) NOT NULL,
    end_at      TIMESTAMP(6),
    all_day     BOOLEAN      NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    category    VARCHAR(50),
    source      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_schedule_start_at ON schedule (start_at);
CREATE INDEX idx_schedule_status ON schedule (status);
