-- 전체 스키마. ver.1 을 내놓기 전이라 여기까지의 마이그레이션 23개를 한 파일로 합쳤다
-- 중간에 만들었다 지운 것(category 테이블, 분류 컬럼, 연기 횟수, 시리즈)은 흔적을 남기지 않는다

-- ── 사용자 ──────────────────────────────────────────────────────────────

-- user 는 SQL 예약어라 테이블명을 app_user 로 둔다
CREATE TABLE app_user (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- OAuth 가 주는 이메일이나 식별자가 들어간다. FieldLengths.USERNAME 과 값이 같아야 한다
    username        VARCHAR(100) NOT NULL UNIQUE,
    display_name    VARCHAR(50),
    -- 폼에 2분 행동 칸을 띄울지. 습관 도구라 켬으로 시작한다
    two_minute_rule BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL
);

-- 인증이 붙기 전까지 애플리케이션은 이 사용자를 현재 사용자로 취급한다
INSERT INTO app_user (username, display_name, created_at, updated_at)
VALUES ('default', '기본 사용자', now(), now());

-- ── 일정 ────────────────────────────────────────────────────────────────

-- 일정의 정체. 반복 여부와 회차별 수행은 아래 두 테이블이 나눠 맡는다
CREATE TABLE schedule (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL REFERENCES app_user (id),

    title             VARCHAR(200) NOT NULL,
    description       TEXT,
    -- 날짜를 아직 안 정한 항목이 있어 선택이다. 없으면 달력에 나오지 않는다
    start_at          TIMESTAMP(6),
    -- 끝나는 시각 대신 길이를 원본으로 삼는다. 반복 회차는 날짜가 매번 다르다
    duration_minutes  INT,
    all_day           BOOLEAN      NOT NULL,

    -- 상위 일정. 부모를 지우면 자식은 남아 최상위로 올라간다
    parent_id         BIGINT       REFERENCES schedule (id) ON DELETE SET NULL,
    due_on            DATE,
    display_order     INT          NOT NULL DEFAULT 0,
    -- MoSCoW. 기본값을 두지 않아 "아직 안 정한 것"과 "Could 로 정한 것"이 구분된다
    priority          VARCHAR(10),

    place             VARCHAR(200),
    two_minute_action VARCHAR(200),
    -- 1회성 일정의 완료는 일정 자체가 갖는다. 반복은 회차가 갖는다
    completed_at      TIMESTAMP(6),

    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_schedule_start_at  ON schedule (start_at);
CREATE INDEX idx_schedule_user_id   ON schedule (user_id);
CREATE INDEX idx_schedule_parent_id ON schedule (parent_id);

-- 반복 규칙. 이 행의 존재 자체가 "반복 여부" 라 별도 플래그를 두지 않는다
CREATE TABLE schedule_recur (
    schedule_id BIGINT       PRIMARY KEY REFERENCES schedule (id) ON DELETE CASCADE,
    freq        VARCHAR(10)  NOT NULL,   -- DAILY / WEEKLY
    by_weekday  VARCHAR(30),             -- "MON,WED,FRI"
    ends_on     DATE,                    -- null 이면 무기한
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL
);

-- 손댄 회차만. 안 건드린 회차는 행이 생기지 않는다
CREATE TABLE schedule_progress (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT       NOT NULL REFERENCES schedule (id) ON DELETE CASCADE,

    -- 회차의 정체성. 규칙이 만들어낸 "원래 날짜" 이고 옮겨도 바뀌지 않는다
    on_date     DATE         NOT NULL,
    status      VARCHAR(20)  NOT NULL,   -- PLANNED / DONE / SKIPPED

    -- null 이면 schedule 값을 쓴다. 값이 있으면 이 회차만 덮어쓴다
    title       VARCHAR(200),
    description TEXT,
    start_at    TIMESTAMP(6),
    end_at      TIMESTAMP(6),

    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,

    -- 회차 하나에 한 줄. 체크가 UPSERT 한 번으로 끝나 원자적이다
    CONSTRAINT uq_progress_occurrence UNIQUE (schedule_id, on_date)
);

-- 조회는 두 축으로 들어온다: 원래 날짜 기준과, 옮겨간 시각 기준
CREATE INDEX idx_progress_on_date  ON schedule_progress (on_date);
CREATE INDEX idx_progress_start_at ON schedule_progress (start_at);
CREATE INDEX idx_progress_status   ON schedule_progress (status);

-- 태그는 일정 단위라 회차별 덮어쓰기를 두지 않는다. 마스터 테이블 없이 문자열만 담는다
CREATE TABLE schedule_tag (
    schedule_id BIGINT      NOT NULL REFERENCES schedule (id) ON DELETE CASCADE,
    name        VARCHAR(50) NOT NULL,
    PRIMARY KEY (schedule_id, name)
);

CREATE INDEX idx_schedule_tag_name ON schedule_tag (name);

-- ── 습관 ────────────────────────────────────────────────────────────────

-- 습관은 일정과 섞지 않는다. 탭을 붙였다 뗄 수 있어야 한다
CREATE TABLE habit (
    id                BIGSERIAL PRIMARY KEY,
    user_id           BIGINT       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    title             VARCHAR(200) NOT NULL,
    category          VARCHAR(20)  NOT NULL,
    two_minute_action VARCHAR(200),
    display_order     INT          NOT NULL DEFAULT 0,
    -- 그만둔 습관도 지난 기록이 남아야 해서 지우는 대신 덮어 둔다
    archived_at       TIMESTAMP,
    created_at        TIMESTAMP    NOT NULL,
    updated_at        TIMESTAMP    NOT NULL
);

CREATE INDEX idx_habit_user_id ON habit (user_id);

-- 한 날에 한 줄. 줄이 있으면 그날 해낸 것이다
CREATE TABLE habit_log (
    id         BIGSERIAL PRIMARY KEY,
    habit_id   BIGINT    NOT NULL REFERENCES habit (id) ON DELETE CASCADE,
    on_date    DATE      NOT NULL,
    note       VARCHAR(200),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_habit_log_day UNIQUE (habit_id, on_date)
);

CREATE INDEX idx_habit_log_on_date ON habit_log (on_date);

-- ── AI ──────────────────────────────────────────────────────────────────

-- 제공자마다 한 줄. 키뿐 아니라 모델과 한도 같은 설정도 담는다
CREATE TABLE ai_provider (
    id                  BIGSERIAL PRIMARY KEY,
    user_id             BIGINT       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    -- 제공자를 가르는 값. 목록을 두지 않아 어느 호환 제공자든 들어온다
    base_url            VARCHAR(300) NOT NULL,
    model               VARCHAR(100) NOT NULL,
    -- AES-GCM 암호문. 원본보다 길어 넉넉히 잡는다
    api_key             VARCHAR(500) NOT NULL,
    -- 이번 달 토큰 한도. NULL 이면 한도 없음
    monthly_token_limit INT,
    created_at          TIMESTAMP    NOT NULL,
    updated_at          TIMESTAMP    NOT NULL,
    CONSTRAINT uq_ai_provider_base_url UNIQUE (user_id, base_url)
);

-- 지금 쓰는 제공자. 비어 있으면 서버 설정(.env)을 쓴다
ALTER TABLE app_user ADD COLUMN active_ai_provider_id BIGINT
    REFERENCES ai_provider (id) ON DELETE SET NULL;

-- AI 호출 한 번에 한 줄. 석 달이 지난 줄은 새 줄을 적을 때 지운다
CREATE TABLE ai_usage (
    id            BIGSERIAL PRIMARY KEY,
    user_id       BIGINT       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    base_url      VARCHAR(300) NOT NULL,
    model         VARCHAR(100) NOT NULL,
    input_tokens  INT          NOT NULL,
    output_tokens INT          NOT NULL,
    created_at    TIMESTAMP    NOT NULL
);

CREATE INDEX idx_ai_usage_user_created ON ai_usage (user_id, created_at);
