-- 갈래를 고정 목록에서 사용자의 것으로 옮긴다.
-- 직접 만들고 지울 수 있어야 하므로 "여섯 개를 안다"는 전제를 버린다.

-- 보이는 이름이 그대로 값이다. 코드 칸을 따로 두지 않는 까닭은, 사용자가 만든 갈래에는
-- 코드를 지어 줄 사람이 없어서다. 습관이 id 로 가리켜 이름을 고쳐도 연결이 끊기지 않는다
CREATE TABLE habit_category (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    name          VARCHAR(50) NOT NULL,
    -- 화면에 늘어놓는 차례. 자리를 바꾸는 길은 아직 없고 심은 순서와 만든 순서로 선다
    display_order INT         NOT NULL DEFAULT 0,
    created_at    TIMESTAMP   NOT NULL,
    updated_at    TIMESTAMP   NOT NULL,
    CONSTRAINT uq_habit_category_name UNIQUE (user_id, name)
);

CREATE INDEX idx_habit_category_user_id ON habit_category (user_id);

-- 쓰고 있던 여섯 갈래를 사람마다 한 벌씩 심는다
INSERT INTO habit_category (user_id, name, display_order, created_at, updated_at)
SELECT u.id, seed.name, seed.ord, now(), now()
FROM app_user u
         CROSS JOIN (VALUES ('운동', 0),
                            ('마음챙김', 1),
                            ('부업', 2),
                            ('예술', 3),
                            ('학습', 4),
                            ('인간관계', 5)) AS seed(name, ord);

ALTER TABLE habit ADD COLUMN category_id BIGINT;

-- 들고 있던 enum 값을 방금 심은 줄에 잇는다
UPDATE habit h
SET category_id = c.id
FROM habit_category c
WHERE c.user_id = h.user_id
  AND c.name = CASE h.category
                   WHEN 'BODY' THEN '운동'
                   WHEN 'MIND' THEN '마음챙김'
                   WHEN 'SIDE_JOB' THEN '부업'
                   WHEN 'ART' THEN '예술'
                   WHEN 'LEARNING' THEN '학습'
                   WHEN 'RELATIONSHIP' THEN '인간관계'
               END;

-- 갈래를 지우면 그 안의 습관도 함께 간다. 습관의 지난 기록은 habit_log 가 이어서 지운다
ALTER TABLE habit
    ALTER COLUMN category_id SET NOT NULL,
    ADD CONSTRAINT fk_habit_category FOREIGN KEY (category_id)
        REFERENCES habit_category (id) ON DELETE CASCADE,
    DROP COLUMN category;

CREATE INDEX idx_habit_category_id ON habit (category_id);
