-- 카테고리를 문자열 컬럼에서 엔티티로 승격한다.
--
-- 계층은 parent_id 로 표현하되, path(전체 경로)를 함께 들고 간다.
-- 이유: "하위 포함 필터"를 재귀 조회 없이 prefix 비교 한 번으로 끝내기 위함.
-- 대신 이름 변경 시 자신과 후손의 path 를 함께 갱신할 책임이 생긴다.
--
-- 주의: 아래 SQL에서 '\' 는 역슬래시 한 글자다
--       (PostgreSQL은 standard_conforming_strings 기본값이 on).

CREATE TABLE category (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50)  NOT NULL,
    parent_id     BIGINT       REFERENCES category (id),
    path          VARCHAR(255) NOT NULL UNIQUE,
    display_order INT          NOT NULL DEFAULT 0,
    color         VARCHAR(20),
    collapsed     BOOLEAN      NOT NULL DEFAULT FALSE,
    archived      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_category_path ON category (path);
CREATE INDEX idx_category_parent_id ON category (parent_id);

-- 기존 schedule.category 문자열을 카테고리 행으로 이관한다.
-- "능력\개발\SpringBoot" 하나에서 상위 경로 3개를 모두 만들어야 계층이 완성된다.
INSERT INTO category (name, path, display_order, collapsed, archived, created_at, updated_at)
SELECT DISTINCT ON (prefix)
       (string_to_array(prefix, '\'))[array_length(string_to_array(prefix, '\'), 1)] AS name,
       prefix,
       0,
       FALSE,
       FALSE,
       now(),
       now()
FROM (
    SELECT array_to_string((string_to_array(s.category, '\'))[1:depth.i], '\') AS prefix
    FROM (SELECT DISTINCT category FROM schedule WHERE category IS NOT NULL AND category <> '') s,
         LATERAL generate_series(1, array_length(string_to_array(s.category, '\'), 1)) AS depth(i)
) expanded
ORDER BY prefix;

-- 부모 연결. 마지막 세그먼트를 떼어낸 경로가 부모의 path 가 된다.
-- 최상위는 떼어낼 것이 없어 자기 자신이 나오므로 마지막 조건으로 걸러진다.
UPDATE category c
SET parent_id = p.id
FROM category p
WHERE p.path = regexp_replace(c.path, '\\[^\\]+$', '')
  AND p.path <> c.path;

-- schedule 을 FK로 연결
ALTER TABLE schedule ADD COLUMN category_id BIGINT;

UPDATE schedule s
SET category_id = c.id
FROM category c
WHERE c.path = s.category;

ALTER TABLE schedule
    ADD CONSTRAINT fk_schedule_category FOREIGN KEY (category_id) REFERENCES category (id);

CREATE INDEX idx_schedule_category_id ON schedule (category_id);

DROP INDEX IF EXISTS idx_schedule_category;
ALTER TABLE schedule DROP COLUMN category;
