-- 사용자 도입 + 카테고리 계층 폐기.
--
-- 변경 요지
--   1) app_user 테이블 신설. 일정과 카테고리의 소유자가 된다.
--   2) 카테고리는 더 이상 별도 엔티티가 아니다. schedule.category 에 문자열로 기록한다.
--   3) 사용자가 고를 수 있는 카테고리 목록은 user_category 에 사용자별로 둔다.
--   4) V3 에서 만든 category 테이블(parent_id, path 기반 계층)은 제거한다.
--
-- 기존 데이터는 전부 보존한다. 계층 경로는 마지막 조각만 남긴다.
--   능력            -> 능력
--   능력\커리어      -> 커리어
--   취미\게임개발    -> 게임개발
--
-- 주의: 아래에서 '\' 는 역슬래시 한 글자다
--       (PostgreSQL 은 standard_conforming_strings 기본값이 on).

-- 1) 사용자 ------------------------------------------------------------
-- user 는 SQL 예약어라 테이블명을 app_user 로 둔다.
CREATE TABLE app_user (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(50),
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL
);

-- 기존 데이터의 소유자가 될 기본 사용자.
-- 인증이 붙기 전까지 애플리케이션은 이 사용자를 현재 사용자로 취급한다.
INSERT INTO app_user (username, display_name, created_at, updated_at)
VALUES ('default', '기본 사용자', now(), now());

-- 2) 사용자별 카테고리 목록 --------------------------------------------
-- 계층이 없다. 이름은 한 사용자 안에서 유일하다.
CREATE TABLE user_category (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES app_user (id),
    name          VARCHAR(50) NOT NULL,
    color         VARCHAR(20),
    display_order INT         NOT NULL DEFAULT 0,
    archived      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_user_category_name UNIQUE (user_id, name)
);

CREATE INDEX idx_user_category_user_id ON user_category (user_id);

-- 기존 category 를 이관한다. 경로의 마지막 조각만 이름으로 쓴다.
-- 서로 다른 경로가 같은 마지막 조각을 가질 수 있으므로(예: 능력\개발, 취미\개발)
-- 이름 기준으로 하나만 남긴다. 먼저 만들어진 것을 우선한다.
INSERT INTO user_category (user_id, name, color, display_order, archived, created_at, updated_at)
SELECT DISTINCT ON (leaf_name)
       (SELECT id FROM app_user WHERE username = 'default'),
       leaf_name,
       color,
       display_order,
       archived,
       created_at,
       updated_at
FROM (
    SELECT (string_to_array(path, '\'))[array_length(string_to_array(path, '\'), 1)] AS leaf_name,
           color, display_order, archived, created_at, updated_at
    FROM category
) flattened
ORDER BY leaf_name, created_at;

-- 3) schedule 에 소유자 추가 -------------------------------------------
ALTER TABLE schedule ADD COLUMN user_id BIGINT;

UPDATE schedule
SET user_id = (SELECT id FROM app_user WHERE username = 'default');

ALTER TABLE schedule ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE schedule
    ADD CONSTRAINT fk_schedule_user FOREIGN KEY (user_id) REFERENCES app_user (id);
CREATE INDEX idx_schedule_user_id ON schedule (user_id);

-- 4) schedule.category 를 문자열로 되돌린다 ----------------------------
ALTER TABLE schedule ADD COLUMN category VARCHAR(50);

UPDATE schedule s
SET category = (
    SELECT (string_to_array(c.path, '\'))[array_length(string_to_array(c.path, '\'), 1)]
    FROM category c
    WHERE c.id = s.category_id
);

ALTER TABLE schedule DROP CONSTRAINT IF EXISTS fk_schedule_category;
DROP INDEX IF EXISTS idx_schedule_category_id;
ALTER TABLE schedule DROP COLUMN category_id;

CREATE INDEX idx_schedule_category ON schedule (category);

-- 5) 계층 기반 category 테이블 제거 ------------------------------------
DROP TABLE category;
