-- 반복 일정. 규칙은 여기에, 실제 회차는 schedule 행으로 미리 만든다.
-- 회차를 미리 만들기 때문에 달력·목록·소유권 필터가 기존 코드 그대로 동작한다.

CREATE TABLE schedule_series (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES app_user (id),
    freq        VARCHAR(10)  NOT NULL,   -- DAILY / WEEKLY
    by_weekday  VARCHAR(30),             -- WEEKLY 일 때 "MON,WED,FRI" (최대 27자)
    starts_on   DATE         NOT NULL,
    ends_on     DATE,                    -- null 이면 무기한 -> 1년치 생성
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL
);

-- 단일 일정은 null 이다. 기존 행도 전부 null 이 되므로 데이터를 건드리지 않는다.
ALTER TABLE schedule ADD COLUMN series_id BIGINT REFERENCES schedule_series (id);

-- 연기 체인. ON DELETE SET NULL 이 필요하다.
-- 시리즈 전체 삭제 때 같은 시리즈의 행들이 서로를 참조하고 있으면
-- 지우는 순서와 무관하게 FK 위반이 난다. 참조가 끊겨도 남은 행 자체는 유효한 기록이다.
ALTER TABLE schedule ADD COLUMN moved_from_id BIGINT
    REFERENCES schedule (id) ON DELETE SET NULL;

CREATE INDEX idx_schedule_series_id ON schedule (series_id);

-- status 는 이미 VARCHAR(20) 이라 POSTPONED(9자)가 그대로 들어간다. 컬럼 변경 없음.
