-- 반복 일정을 "회차를 미리 만드는" 방식에서 "규칙 + 손댄 회차만 기록" 으로 바꾼다.
-- V6 이 만든 schedule_series 는 한 번도 사용된 적이 없으므로 DROP 후 재생성한다.

-- V6 이 추가했으나 이 방식에서는 쓰이지 않는다. 반복 회차는 더 이상 schedule 행이 아니다.
ALTER TABLE schedule DROP COLUMN moved_from_id;
ALTER TABLE schedule DROP COLUMN series_id;
DROP TABLE schedule_series;

-- 규칙 + 템플릿.
-- 회차 행이 없으므로 제목·시각·분류의 "진실" 이 여기로 옮겨온다.
CREATE TABLE schedule_series (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL REFERENCES app_user (id),

    freq             VARCHAR(10)  NOT NULL,   -- DAILY / WEEKLY
    by_weekday       VARCHAR(30),             -- "MON,WED,FRI"
    starts_on        DATE         NOT NULL,
    ends_on          DATE,                    -- null 이면 무기한

    title            VARCHAR(200) NOT NULL,
    description      TEXT,
    -- 날짜는 규칙이 정한다. 시리즈는 "몇 시에 얼마나" 만 안다.
    start_time       TIME         NOT NULL,
    duration_minutes INT,                     -- null 이면 종료 시각 없음
    all_day          BOOLEAN      NOT NULL,
    category         VARCHAR(50),

    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_series_user_id ON schedule_series (user_id);

-- 손댄 회차만. 안 건드린 회차는 행이 생기지 않는다.
CREATE TABLE schedule_override (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id      BIGINT       NOT NULL REFERENCES schedule_series (id) ON DELETE CASCADE,

    -- 회차의 정체성. 규칙이 만들어낸 "원래 날짜" 이고 연기해도 바뀌지 않는다.
    on_date        DATE         NOT NULL,

    status         VARCHAR(20)  NOT NULL,     -- PLANNED / DONE / SKIPPED
    postpone_count INT          NOT NULL DEFAULT 0,

    -- null 이면 시리즈 값을 쓴다. 값이 있으면 이 회차만 덮어쓴다.
    title          VARCHAR(200),
    description    TEXT,
    start_at       TIMESTAMP(6),
    end_at         TIMESTAMP(6),
    category       VARCHAR(50),

    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,

    -- 회차 하나에 override 하나. 체크가 UPSERT 한 번으로 끝나 원자적이다.
    CONSTRAINT uq_override_occurrence UNIQUE (series_id, on_date)
);

-- 조회는 두 축으로 들어온다: 원래 날짜 기준과, 미뤄서 옮겨간 시각 기준.
CREATE INDEX idx_override_on_date  ON schedule_override (on_date);
CREATE INDEX idx_override_start_at ON schedule_override (start_at);

-- 단일 일정의 연기도 override 와 같은 방식으로 맞춘다.
-- original_start_at 은 첫 연기 때만 채운다. null 이면 한 번도 안 미룬 것이다.
ALTER TABLE schedule ADD COLUMN postpone_count    INT NOT NULL DEFAULT 0;
ALTER TABLE schedule ADD COLUMN original_start_at TIMESTAMP(6);

-- ScheduleStatus 의 POSTPONED 는 코드에서 제거한다.
-- status 컬럼에 CHECK 제약이 없으므로 DB 변경은 필요 없다.
