-- 일정을 세 축으로 재편한다.
--
--   schedule           일정의 정체     - 무엇인가
--   schedule_recur     반복 규칙       - 언제 반복되나 (없으면 1회성)
--   schedule_progress  회차별 수행     - 어떻게 됐나 (없으면 PLANNED)
--
-- V7 까지는 단일 일정(schedule)과 반복(schedule_series)이 서로 모르는 두 갈래였고
-- title·category·all_day 를 각각 중복으로 들고 있었다. 그래서 조회할 때 메모리에서
-- 합쳐야 했고, status 가 두 곳에 있었고, 회차 식별자가 id 또는 seriesId+onDate 로 갈렸다.
--
-- 이제 단일 일정은 "1회짜리 일정" 이 되어 회차 식별자가
-- scheduleId + onDate 하나로 통일된다.

-- ── 1. 새 테이블 ────────────────────────────────────────────────────────

-- 반복 규칙. schedule 과 1:1 이고, 이 행의 존재 자체가 "반복 여부" 다.
-- 별도 플래그를 두면 플래그는 true 인데 규칙이 없는 상태가 생길 수 있다.
CREATE TABLE schedule_recur (
    schedule_id BIGINT       PRIMARY KEY REFERENCES schedule (id) ON DELETE CASCADE,
    freq        VARCHAR(10)  NOT NULL,   -- DAILY / WEEKLY
    by_weekday  VARCHAR(30),             -- "MON,WED,FRI"
    ends_on     DATE,                    -- null 이면 무기한
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL
);

-- 손댄 회차만. 안 건드린 회차는 행이 생기지 않는다.
CREATE TABLE schedule_progress (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id    BIGINT       NOT NULL REFERENCES schedule (id) ON DELETE CASCADE,

    -- 회차의 정체성. 규칙이 만들어낸 "원래 날짜" 이고 연기해도 바뀌지 않는다.
    on_date        DATE         NOT NULL,

    status         VARCHAR(20)  NOT NULL,   -- PLANNED / DONE / SKIPPED
    postpone_count INT          NOT NULL DEFAULT 0,

    -- null 이면 schedule 값을 쓴다. 값이 있으면 이 회차만 덮어쓴다.
    title          VARCHAR(200),
    description    TEXT,
    start_at       TIMESTAMP(6),
    end_at         TIMESTAMP(6),
    category       VARCHAR(50),

    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,

    CONSTRAINT uq_progress_occurrence UNIQUE (schedule_id, on_date)
);

-- 조회는 두 축으로 들어온다: 원래 날짜 기준과, 미뤄서 옮겨간 시각 기준.
CREATE INDEX idx_progress_on_date  ON schedule_progress (on_date);
CREATE INDEX idx_progress_start_at ON schedule_progress (start_at);

-- ── 2. schedule 에 소요시간 도입 ────────────────────────────────────────

-- end_at(절대 시각) 대신 duration_minutes(길이)를 원본으로 삼는다.
-- 반복 회차는 날짜가 매번 다르므로 절대 시각은 첫 회차에만 쓸모가 있다.
ALTER TABLE schedule ADD COLUMN duration_minutes INT;

UPDATE schedule
   SET duration_minutes = (EXTRACT(EPOCH FROM (end_at - start_at)) / 60)::INT
 WHERE end_at IS NOT NULL;

-- ── 3. 기존 단일 일정의 수행 상태를 progress 로 옮긴다 ──────────────────
-- 반드시 4단계(시리즈를 schedule 로 옮기기) 보다 먼저 실행해야 한다.
-- 그러지 않으면 시리즈에서 새로 생긴 schedule 행에도 progress 가 붙는다.

INSERT INTO schedule_progress
    (schedule_id, on_date, status, postpone_count, created_at, updated_at)
SELECT id,
       -- 미뤄진 일정은 원래 계획일이 회차의 정체성이다
       COALESCE(original_start_at, start_at)::DATE,
       status,
       postpone_count,
       created_at,
       updated_at
  FROM schedule;

-- 미뤄진 단일 일정은 옮겨간 시각을 덮어쓰기로 남긴다
UPDATE schedule_progress p
   SET start_at = s.start_at,
       end_at   = s.end_at
  FROM schedule s
 WHERE p.schedule_id = s.id
   AND s.original_start_at IS NOT NULL;

-- ── 4. 반복 시리즈를 schedule + schedule_recur 로 옮긴다 ────────────────

-- 옛 시리즈 id 를 잠깐 들고 있어야 override 를 따라 옮길 수 있다
ALTER TABLE schedule ADD COLUMN legacy_series_id BIGINT;

INSERT INTO schedule
    (user_id, title, description, start_at, duration_minutes, all_day, category,
     status, postpone_count, created_at, updated_at, legacy_series_id)
SELECT user_id,
       title,
       description,
       -- DATE + TIME = TIMESTAMP. 첫 회차의 시각이자 반복 시작점
       (starts_on + start_time),
       duration_minutes,
       all_day,
       category,
       'PLANNED',   -- 9단계에서 컬럼째 사라진다
       0,
       created_at,
       updated_at,
       id
  FROM schedule_series;

INSERT INTO schedule_recur
    (schedule_id, freq, by_weekday, ends_on, created_at, updated_at)
SELECT s.id, ss.freq, ss.by_weekday, ss.ends_on, ss.created_at, ss.updated_at
  FROM schedule s
  JOIN schedule_series ss ON ss.id = s.legacy_series_id;

INSERT INTO schedule_progress
    (schedule_id, on_date, status, postpone_count,
     title, description, start_at, end_at, category, created_at, updated_at)
SELECT s.id, o.on_date, o.status, o.postpone_count,
       o.title, o.description, o.start_at, o.end_at, o.category,
       o.created_at, o.updated_at
  FROM schedule_override o
  JOIN schedule s ON s.legacy_series_id = o.series_id;

ALTER TABLE schedule DROP COLUMN legacy_series_id;

-- ── 5. 옛 구조 제거 ────────────────────────────────────────────────────

DROP TABLE schedule_override;
DROP TABLE schedule_series;

-- status·postpone_count·original_start_at 은 schedule_progress 로 옮겨갔다.
-- end_at 은 duration_minutes 가 대신한다.
ALTER TABLE schedule DROP COLUMN status;
ALTER TABLE schedule DROP COLUMN postpone_count;
ALTER TABLE schedule DROP COLUMN original_start_at;
ALTER TABLE schedule DROP COLUMN end_at;

-- status 인덱스는 대상 컬럼이 사라졌으므로 함께 없어진다(자동).
-- 새 자리에 다시 건다.
CREATE INDEX idx_progress_status ON schedule_progress (status);
